// <auto-generated />
using System;
using AutoStatsQC.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoStatsQC.Infrastructure.Migrations
{
    [DbContext(typeof(AutoStatsDbContext))]
    partial class AutoStatsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AutoStatsQC.Domain.Entities.VehicleRegistrationStatistic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FuelType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.Property<string>("VehicleType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.Property<DateTime>("importedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("VehicleRegistrationStatistics", (string)null);
                });

            modelBuilder.Entity("AutoStatsQC.Domain.Entities.VehicleRegistrationStatistic", b =>
                {
                    b.OwnsOne("AutoStatsQC.Domain.ValueObjects.Province", "Province", b1 =>
                        {
                            b1.Property<int>("VehicleRegistrationStatisticId")
                                .HasColumnType("int");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Province");

                            b1.HasKey("VehicleRegistrationStatisticId");

                            b1.ToTable("VehicleRegistrationStatistics", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("VehicleRegistrationStatisticId");
                        });

                    b.Navigation("Province")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
